# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
