# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='Imagenes',
        ),
    ]
