# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180818_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagenes',
            new_name='Foto',
        ),
    ]
