# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
