# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180825_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usergallery',
        ),
    ]
