# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180825_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usergallery',
            new_name='User',
        ),
    ]
