# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180826_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usergallery',
            name='category',
        ),
        migrations.AddField(
            model_name='usergallery',
            name='user_session',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
