# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180905_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='type',
            new_name='typemultimedia',
        ),
    ]
